#!/bin/bash

echo "Test list:"
ls ./testData
echo -n "Which attempt? - all?: "
read which


tmp="all"

# all case
if [ ${which} = ${tmp} ]; then
  exit

# one case
elif [ ${which} ]; then
  echo $which > tmp
  ./simulate_unit

else
  exit

fi
