#!/bin/bash
which=$(<tmp)
rm tmp
clear
echo "[$which] file is attempted...."

echo "---[$which] conponents:---"
cat ./testData/$which
echo
echo "---result:---"

python ~/Desktop/ie03project-tsujigiri/3.Implement/src/main.py < ~/Desktop/ie03project-tsujigiri/4.Test/testData/$which > result
cat result
