#!/bin/bash

ls ./testData
echo -n "Which attempt? - all?: "
read which

tmp="all"

# all case
if [ ${which} = ${tmp} ]; then
  ./simulate_all

# one case
elif [ ${which} ]; then
  echo $which > tmp
  ./simulate_unit

else
  exit

fi
